### ISSUE TITLE
Hash checking: respect third party indices

### ISSUE THREAD

**Issue by carl-armis** [pypa/pip-audit#433]
**Is your feature request related to a problem? Please describe.**
Yes.

Currently if you are using a privately hosted repo and building your own wheels for various projects, you cannot use `pip-audit -s pypi`, while only listing the hashes of your privately hosted wheels.  This leaves us with 2 options.  Adding the upstream digest hash ( that we dont use ) to our hash list for each package. Or using `-s osv`.  

Currently we are using osv. And though I am unsure if this is inferior.  We would like to use the default where we can. 

**Describe the solution you'd like**

Ideally - https://github.com/pypa/pip-audit/blob/76e4fa4a0ed005f543701d4b60c02c75c5b539d2/pip_audit/_service/pypi.py#L89

Would have logic have a flag around it to disable hash checking for situations like this.

**Describe alternatives you've considered**

As mentioned above using `-s osv`

**Additional context**

Example of current failure:
```DEBUG:cachecontrol.controller:Looking up "https://pypi.org/pypi/adal/1.2.2/json" in the cache
DEBUG:cachecontrol.controller:No cache entry available
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): pypi.org:443
DEBUG:urllib3.connectionpool:https://pypi.org:443 "GET /pypi/adal/1.2.2/json HTTP/1.1" 200 1128
DEBUG:cachecontrol.controller:Updating cache with response from "https://pypi.org/pypi/adal/1.2.2/json"
DEBUG:cachecontrol.controller:etag object cached for 1209600 seconds
DEBUG:cachecontrol.controller:Caching due to etag
DEBUG:cachecontrol.controller:Looking up "https://pypi.org/pypi/aenum/3.1.0/json" in the cache
DEBUG:cachecontrol.controller:No cache entry available
DEBUG:urllib3.connectionpool:https://pypi.org:443 "GET /pypi/aenum/3.1.0/json HTTP/1.1" 200 2235
DEBUG:cachecontrol.controller:Updating cache with response from "https://pypi.org/pypi/aenum/3.1.0/json"
DEBUG:cachecontrol.controller:etag object cached for 1209600 seconds
DEBUG:cachecontrol.controller:Caching due to etag
DEBUG:cachecontrol.controller:Looking up "https://pypi.org/pypi/aiobotocore/1.2.2/json" in the cache
DEBUG:cachecontrol.controller:No cache entry available
DEBUG:urllib3.connectionpool:https://pypi.org:443 "GET /pypi/aiobotocore/1.2.2/json HTTP/1.1" 200 5390
DEBUG:cachecontrol.controller:Updating cache with response from "https://pypi.org/pypi/aiobotocore/1.2.2/json"
DEBUG:cachecontrol.controller:etag object cached for 1209600 seconds
DEBUG:cachecontrol.controller:Caching due to etag
Traceback (most recent call last):
  File "/Users/carl.gill/.pyenv/versions/3.7.3/bin/pip-audit", line 8, in <module>
    sys.exit(audit())
  File "/Users/carl.gill/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip_audit/_cli.py", line 439, in audit
    for (spec, vulns) in auditor.audit(source):
  File "/Users/carl.gill/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip_audit/_audit.py", line 67, in audit
    for dep, vulns in self._service.query_all(specs):
  File "/Users/carl.gill/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip_audit/_service/interface.py", line 156, in query_all
    yield self.query(spec)
  File "/Users/carl.gill/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pip_audit/_service/pypi.py", line 101, in query
    f"Mismatched hash for {spec.canonical_name} ({spec.version}): listed "
pip_audit._service.interface.ServiceError: Mismatched hash for aiobotocore (1.2.2): listed 290833e77f3992cf947279106e43f97dc66f72731cf6818d89a171295bda79ba of type sha256 could not be found in PyPI releases```

**Comment by woodruffw** [comment]
Thanks for the request!

Can you clarify your current inputs? The reason we require "all or none" hashes is because it's what `pip` does: if *any* of your dependencies is hashed, then `pip install -r ...` should fail unless *all* are hashed.

Are you using something other than `pip install -r ...` to install your requirements?

**Comment by carl-armis** [comment]
pip-audit --index-url https://<name>.jfrog.io/<name>/api/pypi/<name>-pypi-virt/simple --extra-index-url https://wheels.dev.<name>.com -r thirdparty/pip/requirements.txt

pip-install -r works fine. It is able to validate all the hashes, as we are using `--only-binary :all:` And all the hashes match.

**Comment by woodruffw** [comment]
Oh, I see what you mean now: your requirements *are* fully hashed, but the only hashes for your third-party wheels are your own hashes. Is that correct?

If so, I think this is a full-on bug on our part: we should be grabbing hashes from your `--extra-index-url` and including them in the hash matching.

**Comment by carl-armis** [comment]
This is correct. 

And looking at the code, you are correct. I only see referencing hashes from https://pypi.org/pypi/

**Comment by woodruffw** [comment]
Thanks for confirming! 

Yes, this is definitely a bug on our part, then. I'll re-categorize and get a fix out for this.

**Comment by carl-armis** [comment]
@woodruffw Feel free to change the title of this to better match the "bug". Not sure it makes sense as is anymore.

**Comment by woodruffw** [comment]
As part of this, I probably need to move hash checking out of the PyPI vulnerability service and into the generic dependency collection layer.

**Comment by tetsuo-cpp** [comment]
> As part of this, we probably need to move hash checking out of the PyPI vulnerability service and into the generic dependency collection layer.

I had a think about this and I don't believe we need to move the hash checking. I assume the reasoning would be that we need to figure out which index a package came from in order to know which index to query. However, the order which `pip` processes indexes is undefined and package names are expected to be unique across indexes. That is, if the same name/version appears on both indexes, they're assumed to be the same package with the same hash, etc. So I think we can just do a simple iteration of index urls in the hash checking code.

From a design perspective, I think this is still the right way to go because:
- The dependency collection layer isn't accessing the JSON API and is instead scraping `<index>/simple` so there's no shared functionality to be had here.
- The dependency collection layer which accesses PyPI is only active with the `-r` flag. However, we'll need to check hashes whenever PyPI is used as a vulnerability service (orthogonal to whether we're auditing a requirements file).

**Comment by tetsuo-cpp** [comment]
> As part of this, we probably need to move hash checking out of the PyPI vulnerability service and into the generic dependency collection layer.

> As part of this, we probably need to move hash checking out of the PyPI vulnerability service and into the generic dependency collection layer.

I had a think about this and I don't believe we need to move the hash checking. I assume the reasoning would be that we need to figure out which index a package came from in order to know which index to query. However, the order which `pip` processes indexes is undefined and package names are expected to be unique across indexes. That is, if the same name/version appears on both indexes, they're assumed to be the same package with the same hash, etc. So I think we can just do a simple iteration of index urls in the hash checking code.

From a design perspective, I think this is still the right way to go because the dependency collection layer isn't accessing the JSON API and is instead scraping `<index>/simple` so there's no shared functionality to be had here.

**Comment by tetsuo-cpp** [comment]
I did a bit of digging and it does seem like we'll need to move the hash checking into the dependency resolution layer. We want to be compatible with alternative indexes like DevPI which don't support the same JSON API that Warehouse does.

One catch is that the `simple` endpoint only gives us sha256 whereas `pip install` allows hashes of type sha256, sha384 and sha512. However, pinning with non-sha256 hashes is already an issue for us because the JSON API only gives us sha256 and md5 (which `pip` doesn't allow for pinning).

I'd say the best plan of attack is to move the hash checking into dependency resolution and to skip and provide a warning for non-sha256 hashes (we should already be doing this).

**Comment by woodruffw** [comment]
> One catch is that the `simple` endpoint only gives us sha256 whereas `pip install` allows hashes of type sha256, sha384 and sha512. However, pinning with non-sha256 hashes is already an issue for us because the JSON API only gives us sha256 and md5 (which `pip` doesn't allow for pinning).
> 

My reading of PEP 503 is that the hash fragment on any distribution can be any valid `hashlib` hash, so md5, sha1, sha512, etc. could theoretically show up. So we do need to handle each of these 🙂

**Comment by tetsuo-cpp** [comment]
> My reading of PEP 503 is that the hash fragment on any distribution can be any valid `hashlib` hash, so md5, sha1, sha512, etc. could theoretically show up. So we do need to handle each of these 🙂

How do you propose doing that? From the `simple` endpoint, we only get sha256 and even with the JSON API, we're only getting sha256 and md5. Given that information, I assume that `pip` is probably hashing the downloaded artifact itself rather than getting the hash information.

**Comment by tetsuo-cpp** [comment]
> My reading of PEP 503 is that the hash fragment on any distribution can be any valid `hashlib` hash, so md5, sha1, sha512, etc. could theoretically show up. So we do need to handle each of these 🙂

How do you propose doing that? From the `simple` endpoint, we only get sha256 and even with the JSON API, we're only getting sha256 and md5. Given that information, I assume that `pip` is probably hashing the downloaded artifact itself rather than getting the hash information.

We could give that a try?

**Comment by woodruffw** [comment]
> How do you propose doing that? From the `simple` endpoint, we only get sha256 and even with the JSON API, we're only getting sha256 and md5. Given that information, I assume that `pip` is probably hashing the downloaded artifact itself rather than getting the hash information from the index.
> 
> 
> 
> We could give that a try?

I *think* we want to avoid downloading and hashing ourselves, since that'll significantly increase the processing time on "fully hashed" dependency trees. 

I think the way I phrased it was a little ambiguous: we should accept whatever hashes the indices give us, in whatever formats they give us (per PEP 503). If we don't get any matching hashes, then we should continue to treat it as a failure (even if the reason for a missing hash is that one index is using a hash function we don't expect.)

If a particular index's simple API is only giving us sha256, that's fine. But we should also make sure whatever we do can handle indices that give us other hashes, since PEP 503 says that any hashlib qualifier is valid. And *if* they give us something other than sha256, it'll likely cause a mismatch error anyways, but we should surface that as a mismatch rather than an unsupported hash (since we *would* match it if, say, the requirements file had sha512 hashes in it instead).

**Comment by tetsuo-cpp** [comment]
@woodruffw 
I had another look at this today. The code was a bit confusing, but I think I can explain `pip`'s behaviour here.

My understanding is that it hashes the wheel/sdist that it downloads and then checks it against the hash supplied in the requirements file. I recall we briefly had a discussion about how that behaviour is unlikely because you could provide a hash that works for an sdist but if dependency resolution chose a wheel, the hash would be incorrect. The answer is that `pip` doesn't care about this and blindly checks the hash against whatever it downloads for that requirement line. I have an example below showing what I mean:

```
(test_env) tetsuo@Alexs-MacBook-Pro pip-audit % cat requirements.txt
# This is a valid hash for the sdist for 1.0.0
pip_audit==1.0.0 --hash=sha256:cb055226e724ee69c511bbdb07b2f6c6e30887929c7da32683fc4523e537bfcf

(test_env) tetsuo@Alexs-MacBook-Pro pip-audit % pip install -r requirements.txt --require-hashes
Collecting pip_audit==1.0.0
  Using cached pip_audit-1.0.0-py3-none-any.whl (49 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pip_audit==1.0.0 from https://files.pythonhosted.org/packages/16/b2/c8a8208030b89825cdc1a4f2edaabf2076ba38ab07e77213fc299cf74d99/pip_audit-1.0.0-py3-none-any.whl (from -r requirements.txt (line 2)):
        Expected sha256 cb055226e724ee69c511bbdb07b2f6c6e30887929c7da32683fc4523e537bfcf
             Got        30f8f156aec6ccb8edbe421f4207d80319bcf631838f4ed3dbf610d537b988f3

(test_env) tetsuo@Alexs-MacBook-Pro pip-audit % pip install --no-binary=:all: -r requirements.txt --require-hashes
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Collecting pip_audit==1.0.0
  Using cached pip-audit-1.0.0.tar.gz (37 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting CacheControl>=0.12.10
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    CacheControl>=0.12.10 from https://files.pythonhosted.org/packages/46/9b/34215200b0c2b2229d7be45c1436ca0e8cad3b10de42cfea96983bd70248/CacheControl-0.12.11.tar.gz (from pip_audit==1.0.0->-r requirements.txt (line 2))
```

I prepared a requirement file that had a valid hash for the sdist of pip-audit v1.0.0. If I do a bare `install -r`, the resolver defaults to choosing the wheel and will complain about a hash mismatch. When I use `--no-binary=:all:`, I force the resolver to choose the sdist and the hash check succeeds (the install fails for other reasons but it's enough to illustrate what I mean).

Now for `pip-audit`, I think we can mimic this behaviour in the dependency collection layer since we're already downloading wheels/sdists to figure out what their sub-dependencies are. I think the part that becomes a bit murky is where and when exactly to calculate the hash since the spot where we download the package is to assembly a candidate that the resolver *might* choose.

Here are some ideas off the top of my head:

- Attach the package data to the candidate. When a candidate is chosen, calculate the hash and compare it to the requirement file. This doesn't seem acceptable because there can be lots of candidates and we'll be keeping a ton of wheels/sdists in memory which can potentially be pretty chunky.
- Calculate the hash for all supported algorithms for all candidates. If we want to abide by PEP 503, this might be an issue since `hashlib` supports a lot of algorithms. Realistically, `pip` only allows a few so we could get away with less. A bit wasteful but better than passing the entire package around.
- Pass a mapping into the resolver to tell it what hash algorithm is used for each package. When building a candidate, we can just calculate the one we need. Then when a candidate gets chosen, we can check that hash against the one in the requirements file. This seems the most reasonable to me at this point.

**Comment by woodruffw** [comment]
Thanks for the detailed summary! That does indeed clear things up -- I thought that `pip` was downloading each candidate and using the hash as part of its selection process, but what it actually does is simpler (and more reasonable) 🙂 

Passing the hash algorithm information for each package into the resolver makes sense to me -- let's go with that for now.

**Comment by tetsuo-cpp** [comment]
Hi @carl-armis. We just cut the 2.4.15 release which we expect to solve your issue.

**Comment by woodruffw** [comment]
Update: we had to yank that release, because it regressed on some other behavior. We'll try to get a more permanent fix out in an upcoming patch.

**Comment by tetsuo-cpp** [comment]
This is done in 2.5.0.
