### ISSUE TITLE
Adding logging when debug is enable

### ISSUE THREAD

**Issue by max246** [pypa/pip-audit#459]
It is handy if you can add some logging to this line which helps to understand what package is pulling the information without guessing what is wrong

https://github.com/pypa/pip-audit/blob/main/pip_audit/_cli.py#L465

I have used this solution to figure out what package was triggering the issue

`logger.debug(f"Auditing {spec.name} ({spec.version})")`

**Comment by woodruffw** [comment]
Thanks for the request. Could you clarify what about the current behavior isn't working for you? Does the current progress bar not freeze on failure and show you which audit was running when the command failed?

(Either way, I'm not opposed to an extra debug log here -- just want to make sure I understand what the problem is!)

**Comment by max246** [comment]
In my case where I had to debug why I had the setuptools flagging even if I had set the correct package, I couldnt figure out which package was getting the information from.
I could enable debug  but what I could see is mostly cachecontrol pulling packages but didnt know which package was coming from.

Adding this line, I was able to identify in few seconds which package was pulling the wrong version.

You can see my logs on my previous ticket: https://github.com/pypa/pip-audit/issues/458

**Comment by woodruffw** [comment]
Makes sense, thank you! Would you mind making a short PR for that debug line? Otherwise, I'll add it sometime tonight or this weekend.

**Comment by woodruffw** [comment]
#460
