### ISSUE TITLE
Allow pip-audit to report the current version of the vuln database

### ISSUE THREAD

**Issue by TansyArron** [pypa/pip-audit#504]
**Is your feature request related to a problem? Please describe.**
I'm integrating pip-audit with our build tool, Pants. Rather than run the tool every time, I'd prefer to run it again only when new vulnerabilities are discovered. 

**Describe the solution you'd like**
I'd like to be able to call something like `pip-audit --db-version` and get back a unique identifier for the current version of the database (something like the etag for https://github.com/pypa/advisory-database/tree/main/vulns would work)

**Describe alternatives you've considered**
* I can check the etag for https://github.com/pypa/advisory-database/tree/main/vulns myself every time
* I can run pip-audit every time and ignore the potential performance improvements of cached results

**Comment by woodruffw** [comment]
Thanks for the request!

Something like this would be interesting, but I think it'd be difficult to do in the current form offered by our backing vulnerability services (PyPI and OSV): both pull from multiple vulnerability DBs and may have updates pushed to them at any point from multiple backing sources.

In particular, checking the ETag for the PyPA advisory database will probably be insufficient, since it's only one of several sources used for the vulnerabilities reported through the PyPI JSON API.

Could you say some more about your use case? `pip-audit` already does some internal caching of requests (and reuses `pip`'s own cache), so repeated audits of the same dependency source should be _relatively_ performant (especially if your dependencies are fully pinned.)

**Comment by woodruffw** [comment]
Closing as not currently actionable: not all vulnerability services are versioned, and our pre-existing caching is performant enough in the pinned deps case.
