### ISSUE TITLE
Enabling pip-audit to be used for dependency extraction purposes only

### ISSUE THREAD

**Issue by iastewar** [pypa/pip-audit#526]
**Is your feature request related to a problem? Please describe.**

It doesn't seem like Python/pip includes an easy way to get the dependency graph. I do not need the vulnerability scanning component of pip-audit. I only need the dependency extraction component. It looks like pip-audit includes its own dependency resolver, requirements parser, and pyproject.toml parser. I can use this information to call vuln APIs myself.

**Describe the solution you'd like**

I would like to be able to use pip-audit for dependency extraction purposes only. It can either be through the CLI or as an importable API. I want 2 things:
1. The dependency graph
2. A map of each dependency to line/column numbers in the requirements.txt and/or pyproject.toml files.

**Describe alternatives you've considered**

I can write my own resolver similar to what pip-audit has already written, but it would be nice if I could reuse this code.

**Comment by woodruffw** [comment]
Thanks for the request!

I think this would fall under our public API plans: we already build the dependency graph internally, so this would mostly just be a matter of determining the shape of the public API that exposes that information.

That being said, it's worth noting that we're actually planning on dropping our custom `resolvelib`-based dependency resolver for a `pip` wrapper, due to correctness issues on some edge cases (see #522). This shouldn't have any significant effect on you as a potential downstream user, however, since we already depend on `pip` and will be fully encapsulating it in a temporary virtual environment.

> 2\. A map of each dependency to line/column numbers in the requirements.txt and/or pyproject.toml files.

This might be a little trickier: we depend on a third-party TOML parser for `pyproject.toml`, and it probably doesn't expose line and column information (at least, not via a public API). The `requirements.txt` parser we use does, though.

**Comment by woodruffw** [comment]
> It doesn't seem like Python/pip includes an easy way to get the dependency graph.

Related to this: have you tried `pip install ... --dry-run --report`? That's probably what `pip-audit` will end up wrapping anyways, and that should produce the dependency set (if not the actual graph structure) in JSON.

**Comment by iastewar** [comment]
Thanks, good to know you are planning a public API! Also no, I didn't know about the `--report` flag. I see that it is new in pip 22.2. Is the plan to somehow create a venv that includes pip 22.2 or higher? If so, how will you accomplish this? Or will users be required to have a pip version greater than or equal to 22.2 installed on their system to use pip-audit?

**Comment by woodruffw** [comment]
> Is the plan to somehow create a venv that includes pip 22.2 or higher?

Yep, exactly! We'll bootstrap the `venv` to have the latest `pip` and `setuptools`, since that's the encouraged practice from upstream.

(`pip-audit` does support older `pip` versions by default, and we'll continue to do so. But the "happy" path will definitely be to bootstrap the latest in a `venv` and use it.)

**Comment by tetsuo-cpp** [comment]
@iastewar As of 2.5.0, `pip-audit` is using the `--dry-run` and `--report` flags. Not sure if you've already got this working for your project, but we have some code that accomplishes it [here](https://github.com/pypa/pip-audit/blob/main/pip_audit/_virtual_env.py#L70) that is pretty straightforward.

**Comment by iastewar** [comment]
> @iastewar As of 2.5.0, `pip-audit` is using the `--dry-run` and `--report` flags. Not sure if you've already got this working for your project, but we have some code that accomplishes it [here](https://github.com/pypa/pip-audit/blob/main/pip_audit/_virtual_env.py#L70) that is pretty straightforward.

Awesome thanks, I think this is exactly what we want! We have put the project on hold temporarily but once we get back to it we will be sure to give this a closer look.

**Comment by woodruffw** [comment]
Hi @iastewar! Any updates here? If not and you still believe that https://github.com/pypa/pip-audit/issues/526#issuecomment-1480818155 addresses your needs, then I'll close this as complete :slightly_smiling_face:
