### ISSUE TITLE
Feature: Filter for Malware or specific vulnerability identifiers

### ISSUE THREAD

**Issue by rclugston-now** [pypa/pip-audit#856]
### Pre-submission checks

- [X] I am **not** reporting a new vulnerability or requesting a new vulnerability identifier. These **must** be reported or managed via upstream dependency sources or services, not this repository.
- [X] I agree to follow the [PSF Code of Conduct](https://www.python.org/psf/conduct/).
- [X] I have looked through the open issues for a duplicate request.

### What's the problem this feature will solve?

It would be nice to have a command line flag to filter for packages containing malware. Within OSV.dev, malware receives the identifier prefix of "MAL-". 

### Describe the solution you'd like

The additional of command line arguments to help confirm vulnerabilities of interest.

Option 1) supply a vulnerability identifier search options:
--id, -i VULNID          Search for the vulnerability identifier specified by VULNID

Option 2) filter just malware
--malware, -m           Filter searches to only malware identifiers which are prefixed with "MAL-"

### Additional context

Recently the [fabrice typo squatting malware](https://socket.dev/blog/malicious-python-package-typosquats-fabric-ssh-library) received an OSV.dev identifier:
https://osv.dev/vulnerability/MAL-2024-10573

Attempting to confirm positive identifications (for just malware) using pip-audit requires additional shell scripting.

**Comment by rclugston-now** [comment]
Understood. It looks like Python advisory DB is missing a lot of details on malicious packages (e.g. typo squatting).

In lieu of a categorical filter, an option to look for specific vulnerability identifiers would be helpful.

**Comment by woodruffw** [comment]
> Understood. It looks like Python advisory DB is missing a lot of details on malicious packages (e.g. typo squatting).

This would be good to raise with them! I don't know whether they consider malicious packages to be within their remit.

> In lieu of a categorical filter, an option to look for specific vulnerability identifiers would be helpful.

This is what we intend the JSON and SBOM outputs for -- I've been hesitant to bake more filtering logic into `pip-audit` itself, since in the general case it starts to resemble predicates, etc. that are best handled by ingesting `pip-audit` into your database of choice and performing queries from there (or doing `| jq <filter>` on the output).

I understand not wanting to write glue code (I don't like writing glue either 🙂), but in a case like this I think it's important for `pip-audit` to define strong boundaries around what it will and won't do, to keep the tool's scope tractable.

**Comment by rclugston-now** [comment]
Your note about using the jq command line was very helpful; I'd missed that detail in the usage docs. Here's the syntax i chose:
`pip-audit -f json 2>/dev/null | jq '.dependencies[].vulns[].id | select(. == "MAL-2024-10573")'`
